on:
  push:
    branches:
      - master
      - main  # Adjust according to your needs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This is important

    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@1.34.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch

    - name: Create New Version Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.bump_version.outputs.tag }} Release
        body: ""
        tag_name: ${{ steps.bump_version.outputs.tag }}
        generate_release_notes: true
        draft: false
        prerelease: true  # set this to true if you want a pre-releas