name: Checks
on:
  pull_request:
    branches:
      - fix_tag
  push:
    branches:
      - fix_tag
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  ci: 
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    # - name : Run EC Validate (keyless)
    #   uses: ./
    #   with:
    #     image: ghcr.io/enterprise-contract/golden-container:latest@sha256:63c006b879ad08aec9a80ed6c340335972311747eb42c83566a1eab46e404c1d # latest
    #     identity: https:\/\/github\.com\/(slsa-framework\/slsa-github-generator|enterprise-contract\/golden-container)\/
    #     issuer: https://token.actions.githubusercontent.com

    #FIXME Commented out because the golden-image on quay.io is failing due to a violation in the image. 
    # - name : Run EC Validate (Long_Lived)
    #   uses: ./
    #   with:
    #     image: quay.io/redhat-appstudio/ec-golden-image:latest
    #     key: ${{ vars.PUBLIC_KEY }}
    #     policy: github.com/enterprise-contract/config//slsa3
    #     extra-params: --ignore-rekor

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: ci 
    # if: needs.ci.outputs.status == 'success' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@1.34.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: true # Set this to true if you want a 'v' prefix in your version tags
        default_bump: patch # Default version bump type if you're not specifying any
        
    - name: Create New Version Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.bump_version.outputs.new_tag }} Release # Use new_tag instead of tag
        body: ""
        tag_name: ${{ steps.bump_version.outputs.new_tag }} # Use new_tag instead of tag
        generate_release_notes: true
        draft: false
        prerelease: false