on:
  push:
    branches:
      - master
      - main  # Adjust according to your needs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Get Latest Version Tag and Increment
      run: |
          latestVTag=$(gh api -H 'Accept: application/vnd.github.v3+json' /repos/${{ github.repository }}/releases/latest -q '.tag_name')
          echo "Latest Version Tag: $latestVTag"
          
          major=$(echo ${latestVTag#v} | awk -F. '{print $1}')
          minor=$(echo ${latestVTag#v} | awk -F. '{print $2}')
          patch=$(echo ${latestVTag#v} | awk -F. '{print $3}')
          
          if [ "$patch" -eq "9" ]; then
            if [ "$minor" -eq "9" ]; then
              major=$((major + 1))
              minor=0
              patch=0
            else
              minor=$((minor + 1))
              patch=0
            fi
          else
            patch=$((patch + 1))
          fi

          echo "newVersion=v$major.$minor.$patch" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ github.token }}
        
    - name: Create New Version Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
          name: ${{ env.newVersion }} Release
          body: ""
          tag_name: ${{ env.newVersion }}
          generate_release_notes: true
          draft: false
          prerelease: false
